name: Daily Content Automation

on:
  schedule:
    - cron: '0 3 * * *'  # Executa às 3h da manhã UTC diariamente
  workflow_dispatch:  # Permite execução manual quando necessário

jobs:
  automate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run content discovery
        run: python youtube_automation/content_discovery.py
        
      - name: Generate script and timestamps
        run: python youtube_automation/script_generator.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
      - name: Generate narration
        run: python youtube_automation/narration_generator.py
        
      - name: Find and process images
        run: python youtube_automation/image_processor.py
        
      - name: Upload to Drive
        run: python clone_drive_uploader/uploader.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}